import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { delimiter, join, normalize, resolve } from "node:path";
import type { WrapperVerificationResult } from "../../shared/types/ipc.js";
import type { ProviderId } from "../../shared/types/provider.js";
import { wrapperVersion as currentWrapperVersion } from "./generator.js";

const supportedProviders = {
  codex: {
    displayName: "Codex",
    executableName: "codex",
    versionArgs: ["--version"]
  },
  gemini: {
    displayName: "Gemini",
    executableName: "gemini",
    versionArgs: ["--version"]
  }
} as const;

const defaultProbeTimeoutMs = 3_000;

export type SupportedVerificationProviderId = keyof typeof supportedProviders;

export type WrapperVerificationStatus =
  | "missing_command"
  | "native_cli_active"
  | "wrapper_active"
  | "stale_wrapper"
  | "unverified";

export interface CommandProbeInput {
  readonly command: string;
  readonly args: readonly string[];
  readonly timeoutMs: number;
}

export interface CommandProbeResult {
  readonly exitStatus: number | null;
  readonly stderr: string;
  readonly stdout: string;
}

export interface VerifyProviderWrapperInput {
  readonly commandResolver: (command: string) => Promise<string | null> | string | null;
  readonly generatedWrapperPath: string;
  readonly nativeCommandPath: string | null;
  readonly providerId: ProviderId;
  readonly readGeneratedWrapper?: (path: string) => Promise<string | null> | string | null;
  readonly runner: (input: CommandProbeInput) => Promise<CommandProbeResult>;
  readonly timeoutMs?: number;
  readonly wrapperVersion: string;
}

export interface WrapperVerificationService {
  readonly verifyWrapper: (providerId: ProviderId) => Promise<WrapperVerificationResult>;
}

export interface WrapperVerificationServiceOptions {
  readonly appUserDataDir: string;
  readonly env?: NodeJS.ProcessEnv;
  readonly platform?: NodeJS.Platform;
  readonly runner?: (input: CommandProbeInput) => Promise<CommandProbeResult>;
  readonly timeoutMs?: number;
  readonly wrapperVersion?: string;
}

export async function verifyProviderWrapper(input: VerifyProviderWrapperInput): Promise<WrapperVerificationResult> {
  const provider = getSupportedProvider(input.providerId);
  const resolvedCommandPath = await input.commandResolver(provider.executableName);
  const generatedWrapperPath = normalizePathForComparison(input.generatedWrapperPath);

  if (!resolvedCommandPath) {
    return createVerificationResult({
      message: `${provider.displayName} command was not found on PATH. Install the native CLI, then add the Accuracy Mode wrapper directory manually.`,
      providerId: input.providerId,
      status: "missing_command",
      verified: false
    });
  }

  const resolvedPath = normalizePathForComparison(resolvedCommandPath);
  const nativePath = input.nativeCommandPath ? normalizePathForComparison(input.nativeCommandPath) : null;
  const pointsAtGeneratedWrapper = resolvedPath === generatedWrapperPath;

  if (!pointsAtGeneratedWrapper) {
    await probeNativeCommand({
      input,
      nativeCommandPath: input.nativeCommandPath ?? resolvedCommandPath,
      provider
    });

    return createVerificationResult({
      message: `${provider.displayName} is installed, but the native CLI is first on PATH. Add the generated Accuracy Mode wrapper directory before the native CLI directory.`,
      providerId: input.providerId,
      status: nativePath && resolvedPath === nativePath ? "native_cli_active" : "unverified",
      verified: false,
      wrapperVersion: input.wrapperVersion
    });
  }

  const detectedWrapperVersion = await readWrapperVersion({
    generatedWrapperPath: input.generatedWrapperPath,
    readGeneratedWrapper: input.readGeneratedWrapper
  });

  if (detectedWrapperVersion && detectedWrapperVersion !== input.wrapperVersion) {
    return createVerificationResult({
      message: `${provider.displayName} Accuracy Mode wrapper is installed, but it was generated by an older app version. Regenerate the wrapper and rerun the manual setup command.`,
      providerId: input.providerId,
      status: "stale_wrapper",
      verified: false,
      wrapperVersion: detectedWrapperVersion
    });
  }

  if (!input.nativeCommandPath) {
    return createVerificationResult({
      message: `${provider.displayName} Accuracy Mode wrapper is first on PATH, but the native CLI target could not be verified.`,
      providerId: input.providerId,
      status: "unverified",
      verified: false,
      wrapperVersion: input.wrapperVersion
    });
  }

  const probe = await probeNativeCommand({
    input,
    nativeCommandPath: input.nativeCommandPath,
    provider
  });

  if (probe.exitStatus !== 0) {
    return createVerificationResult({
      message: `${provider.displayName} Accuracy Mode wrapper is first on PATH, but the native CLI version check did not complete successfully.`,
      providerId: input.providerId,
      status: "unverified",
      verified: false,
      wrapperVersion: input.wrapperVersion
    });
  }

  return createVerificationResult({
    message: `${provider.displayName} Accuracy Mode wrapper is active.`,
    providerId: input.providerId,
    status: "wrapper_active",
    verified: true,
    wrapperVersion: input.wrapperVersion
  });
}

export function createWrapperVerificationService(
  options: WrapperVerificationServiceOptions
): WrapperVerificationService {
  const platform = options.platform ?? process.platform;
  const env = options.env ?? process.env;
  const runner = options.runner ?? runCommandProbe;
  const version = options.wrapperVersion ?? currentWrapperVersion;
  const wrapperRoot = join(options.appUserDataDir, "wrappers");

  return {
    verifyWrapper: async (providerId: ProviderId): Promise<WrapperVerificationResult> => {
      const provider = getSupportedProvider(providerId);
      const generatedWrapperPath = join(
        wrapperRoot,
        providerId,
        platform === "win32" ? `${provider.executableName}.cmd` : provider.executableName
      );

      return verifyProviderWrapper({
        commandResolver: (command) =>
          resolveCommandPath(command, {
            env,
            platform
          }),
        generatedWrapperPath,
        nativeCommandPath: resolveCommandPath(provider.executableName, {
          env,
          platform,
          excludedRoot: wrapperRoot
        }),
        providerId,
        readGeneratedWrapper: readWrapperFileIfPresent,
        runner,
        timeoutMs: options.timeoutMs,
        wrapperVersion: version
      });
    }
  };
}

async function probeNativeCommand(input: {
  readonly input: VerifyProviderWrapperInput;
  readonly nativeCommandPath: string;
  readonly provider: (typeof supportedProviders)[SupportedVerificationProviderId];
}): Promise<CommandProbeResult> {
  return input.input.runner({
    args: input.provider.versionArgs,
    command: input.nativeCommandPath,
    timeoutMs: input.input.timeoutMs ?? defaultProbeTimeoutMs
  });
}

function resolveCommandPath(
  executableName: string,
  input: {
    readonly env: NodeJS.ProcessEnv;
    readonly excludedRoot?: string;
    readonly platform: NodeJS.Platform;
  }
): string | null {
  const pathValue = input.env.PATH ?? input.env.Path ?? input.env.path;
  if (!pathValue) {
    return null;
  }

  const executableNames = input.platform === "win32" ? createWindowsExecutableNames(executableName, input.env) : [executableName];
  const excludedRoot = input.excludedRoot ? normalizePathForComparison(input.excludedRoot) : null;

  for (const dir of pathValue.split(delimiter).filter(Boolean)) {
    if (excludedRoot && normalizePathForComparison(dir).startsWith(excludedRoot)) {
      continue;
    }

    for (const candidateName of executableNames) {
      const candidate = join(dir, candidateName);
      if (existsSync(candidate)) {
        return candidate;
      }
    }
  }

  return null;
}

function createWindowsExecutableNames(executableName: string, env: NodeJS.ProcessEnv): readonly string[] {
  const pathExt = env.PATHEXT ?? ".COM;.EXE;.BAT;.CMD";
  return [
    executableName,
    ...pathExt
      .split(";")
      .filter(Boolean)
      .flatMap((extension) => [
        `${executableName}${extension.toLowerCase()}`,
        `${executableName}${extension.toUpperCase()}`
      ])
  ];
}

async function readWrapperVersion(input: {
  readonly generatedWrapperPath: string;
  readonly readGeneratedWrapper?: (path: string) => Promise<string | null> | string | null;
}): Promise<string | null> {
  const content = await input.readGeneratedWrapper?.(input.generatedWrapperPath);
  if (!content) {
    return null;
  }

  return (
    content.match(/_cu_version='([^']+)'/u)?.[1] ??
    content.match(/CLAUDE_USAGE_WRAPPER_VERSION=([^"\r\n]+)/u)?.[1] ??
    null
  );
}

async function readWrapperFileIfPresent(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

async function runCommandProbe(input: CommandProbeInput): Promise<CommandProbeResult> {
  return new Promise((resolveProbe) => {
    const child = spawn(input.command, [...input.args], {
      env: process.env,
      stdio: ["ignore", "pipe", "pipe"]
    });
    const timeout = setTimeout(() => {
      child.kill("SIGTERM");
    }, input.timeoutMs);
    const stdoutChunks: Buffer[] = [];
    const stderrChunks: Buffer[] = [];

    child.stdout.on("data", (chunk: Buffer) => {
      stdoutChunks.push(chunk);
    });
    child.stderr.on("data", (chunk: Buffer) => {
      stderrChunks.push(chunk);
    });
    child.on("error", () => {
      clearTimeout(timeout);
      resolveProbe({ exitStatus: null, stderr: "", stdout: "" });
    });
    child.on("close", (exitStatus) => {
      clearTimeout(timeout);
      resolveProbe({
        exitStatus,
        stderr: stderrChunks.join("").slice(0, 256),
        stdout: stdoutChunks.join("").slice(0, 256)
      });
    });
  });
}

function createVerificationResult(input: {
  readonly message: string;
  readonly providerId: ProviderId;
  readonly status: WrapperVerificationStatus;
  readonly verified: boolean;
  readonly wrapperVersion?: string;
}): WrapperVerificationResult {
  return {
    message: sanitizeMessage(input.message),
    providerId: input.providerId,
    status: input.status,
    verified: input.verified,
    ...(input.wrapperVersion ? { wrapperVersion: input.wrapperVersion } : {})
  };
}

function getSupportedProvider(providerId: ProviderId): (typeof supportedProviders)[SupportedVerificationProviderId] {
  assertSupportedProviderId(providerId);
  return supportedProviders[providerId];
}

function assertSupportedProviderId(providerId: ProviderId): asserts providerId is SupportedVerificationProviderId {
  if (providerId === "codex" || providerId === "gemini") {
    return;
  }
  throw new Error(`Unsupported Accuracy Mode wrapper provider: ${providerId}`);
}

function sanitizeMessage(value: string): string {
  return value
    .replace(/access[_-]?token/giu, "redacted credential")
    .replace(/session[_-]?key/giu, "redacted credential")
    .replace(/cookie/giu, "redacted credential")
    .replace(/prompt/giu, "input")
    .replace(/stdout|raw stderr/giu, "command output");
}

function normalizePathForComparison(value: string): string {
  return normalize(resolve(value)).replaceAll("\\", "/").replace(/\/+$/u, "").toLowerCase();
}
